kind: pipeline
name: amd64
platform:
  os: linux
  arch: amd64
steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: docker.io/jakolehm/cfssl
      auto_tag_suffix: linux-amd64
---
kind: pipeline
name: arm64
platform:
  os: linux
  arch: arm64
steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: docker.io/jakolehm/cfssl
      auto_tag_suffix: linux-arm64
