kind: pipeline
name: amd64
platform:
  os: linux
  arch: amd64
steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: docker.io/jakolehm/cfssl-amd64
      auto_tag: true
---
kind: pipeline
name: arm64
platform:
  os: linux
  arch: arm64
steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: docker.io/jakolehm/cfssl-arm64
      auto_tag: true
---
kind: pipeline
name: manifest
platform:
  os: linux
  arch: amd64
depends_on:
  - amd64
  - arm64
steps:
  - name: manifest
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: jakolehm/cfssl
      spec: manifest.tpl
      platforms:
        - linux/amd64
        - linux/arm64
