kind: pipeline
name: default
platform:
  os: linux
  arch: amd64
steps:
  - name: amd64
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: docker.io/jakolehm/cfssl
      auto_tag_suffix: linux-amd64
  - name: arm64
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: docker.io/jakolehm/cfssl
      auto_tag_suffix: linux-arm64
      build_args:
      - ARCH=arm64
  - name: manifest
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: jakolehm/cfssl:${DRONE_TAG}
      template: jakolehm/cfssl:${DRONE_TAG}-OS-ARCH
      auto_tag: true
      platforms:
        - linux/amd64
        - linux/arm64
